steps:
- name: node:12
  id: Install
  entrypoint: npm
  args: ['install']
- name: node:12
  id: Test
  entrypoint: npm
  args: ['test']
- name: node:12
  id: Build
  entrypoint: npm
  args: ['run', 'build']
- name: node:12
  id: Prune
  entrypoint: npm
  args: ['prune', '--production']
- name: gcr.io/$PROJECT_ID/envsubst
  id: Substitute
  env: ['SERVICE_IP=$_SERVICE_IP']
  args: ['app.yaml']
- name: ubuntu
  args: ['ls']
- name: ubuntu
  args: ['ls', 'node_modules']
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args: ['app', 'deploy']
