steps:
- name: node:12
  id: Install
  entrypoint: npm
  args: ['install']
- name: node:12
  id: Test
  entrypoint: npm
  args: ['test']
- name: node:12
  id: Build
  entrypoint: npm
  args: ['run', 'build']
- name: node:12
  id: Prune
  entrypoint: npm
  args: ['prune', '--production']
- name: 'gcr.io/cloud-builders/gcloud'
  id: Deploy
  args: ['app', 'deploy']
